[package]
name = "metallica-seattle-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.1"
rocket_dyn_templates = { version = "0.2.0", features = [ "tera" ] }
shuttle-rocket = "0.48.0"
shuttle-runtime = "0.48.0"
